### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._internal.cli.main'

### ISSUE THREAD

**Issue by nilinswap** [wilspi/django-templatestore#80]
Went through whole of [this](https://gist.github.com/wilspi/aad81f832d030d80fca91dfa264a1f8a) gist and found pip not working. 
`django-templatestore/django-templatestore-dev/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'`

**Comment by wilspi** [comment]
How are you running this? 
`python -m pip install -r requirements.txt` should work

**Comment by wilspi** [comment]
Thanks @nilinswap , have updated this in readme

**Comment by wilspi** [comment]
Thanks @nilinswap , have fixed this to work with `pip`, also updated in readme
